#!/usr/bin/env Rscript

# Kaiaulu - https://github.com/sailuh/kaiaulu
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

suppressPackageStartupMessages({
  require(yaml, quietly = TRUE)
  require(data.table, quietly = TRUE)
})

# Build CLI usage/help text for -h/--help
usage <- paste(
  "USAGE:",
  "  Rscript exec/conf.R [--source=mysql] [--template=<template_yml>] [--out=<conf_dir>] [--apply] [--no-prune] [--verify-api] [--token-path=<path>] [--sample-size=<n>] [--max-forks=<n>] [--verbose]",
  "",
  "DESCRIPTION:",
  "  Generates YAML configs using MySQL with canonical + fork-only policy.",
  "",
  "  Naming policy:",
  "    - repo.yml if owner == repo",
  "    - repo_owner.yml otherwise",
  "",
  "  Output policy:",
  "    - writes files into conf/ by default",
  "    - backup-then-replace for existing target files",
  "    - deletes out-of-scope YAML files only if previously generated by this script",
  "",
  "MYSQL ENV VARS:",
  "  MYSQL_HOST, MYSQL_PORT, MYSQL_DB, MYSQL_USER, MYSQL_PASSWORD",
  "",
  "DEFAULTS:",
  "  --source=mysql",
  "  --template=conf/trinitycore.yml",
  "  --out=conf",
  "  --token-path=~/.ssh/github_token",
  "  --sample-size=3",
  "  --max-forks=0 (0 = no limit)",
  "  dry-run unless --apply is provided",
  sep = "\n"
)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 0 || any(args %in% c("-h", "--help"))) {
  cat(usage, "\n")
  quit(save = "no", status = 0)
}

# Parse CLI args, flags only (e.g. --apply) and key-value pairs (e.g. --template=path)
flags <- args[startsWith(args, "--")]

extract_flag_value <- function(flags, key, default_value = NULL) {
  prefix <- paste0("--", key, "=")
  matched <- flags[startsWith(flags, prefix)]
  if (length(matched) == 0) {
    return(default_value)
  }
  sub(prefix, "", matched[[1]])
}

# Resolve CLI configuration (source, paths, modes)
source_mode <- tolower(extract_flag_value(flags, "source", "mysql"))
template_path <- extract_flag_value(flags, "template", "conf/trinitycore.yml") # Default template with all possible fields for GitHub projects
out_dir <- extract_flag_value(flags, "out", "conf")
backup_dir <- extract_flag_value(flags, "backup-dir", NULL)
apply_changes <- "--apply" %in% flags
verbose <- "--verbose" %in% flags
prune_out_of_scope <- !("--no-prune" %in% flags)
verify_api <- "--verify-api" %in% flags
token_path <- extract_flag_value(flags, "token-path", "~/.ssh/github_token") # Default path for GitHub token used in API validation
sample_size <- as.integer(extract_flag_value(flags, "sample-size", "3"))
max_forks <- as.integer(extract_flag_value(flags, "max-forks", "0"))

if (source_mode != "mysql") {
  stop("--source must be mysql")
}

if (!file.exists(template_path)) {
  stop("Template YAML not found: ", template_path)
}
if (!dir.exists(out_dir)) {
  stop("Output directory not found: ", out_dir)
}
if (!is.null(backup_dir) && !dir.exists(backup_dir) && apply_changes) {
  dir.create(backup_dir, recursive = TRUE, showWarnings = FALSE)
}

# Header comments added to the top of each generated YAML file
# Marker line is used to identify files generated by this script for safe pruning
generated_marker <- "# Generated by exec/conf.R"
yaml_header <- paste(
  "# -*- yaml -*-",
  "# https://github.com/sailuh/kaiaulu",
  generated_marker,
  "#",
  "# Copying and distribution of this file, with or without modification,",
  "# are permitted in any medium without royalty provided the copyright",
  "# notice and this notice are preserved.  This file is offered as-is,",
  "# without any warranty.",
  "",
  "# Project Configuration File #",
  "#",
  "# To perform analysis on open source projects, you need to manually",
  "# collect some information from the project's website. As there is",
  "# no standardized website format, this file serves to distill",
  "# important data source information so it can be reused by others",
  "# and understood by Kaiaulu.",
  "#",
  "# Please check https://github.com/sailuh/kaiaulu/tree/master/conf to",
  "# see if a project configuration file already exists. Otherwise, we",
  "# would appreciate if you share your curated file with us by sending a",
  "# Pull Request: https://github.com/sailuh/kaiaulu/pulls",
  "#",
  "# Note, you do NOT need to specify this entire file to conduct analysis.",
  "# Each R Notebook uses a different portion of this file. To know what",
  "# information is used, see the project configuration file section at",
  "# the start of each R Notebook.",
  "#",
  "# Please comment unused parameters instead of deleting them for clarity.",
  "# If you have questions, please open a discussion:",
  "# https://github.com/sailuh/kaiaulu/discussions",
  sep = "\n"
)

build_filename <- function(owner, repo) {
  if (owner == repo) {
    return(paste0(repo, ".yml"))
  }
  paste0(repo, "_", owner, ".yml")
}

# Populate the template with repo-specific paths
build_conf <- function(template_conf, owner, repo) {
  conf <- template_conf

  if (is.null(conf$project)) conf$project <- list()
  conf$project$website <- sprintf("https://github.com/%s/%s", owner, repo)

  if (is.null(conf$issue_tracker)) conf$issue_tracker <- list()
  if (is.null(conf$issue_tracker$github)) conf$issue_tracker$github <- list()
  if (is.null(conf$issue_tracker$github$project_key_1)) conf$issue_tracker$github$project_key_1 <- list()

  conf$issue_tracker$github$project_key_1$owner <- owner
  conf$issue_tracker$github$project_key_1$repo <- repo

  base_path <- sprintf("rawdata/github/%s/%s", owner, repo)
  conf$issue_tracker$github$project_key_1$issue_or_pr_comment <- sprintf("%s/issue_or_pr_comment/", base_path)
  conf$issue_tracker$github$project_key_1$issue_event <- sprintf("%s/issue_event/", base_path)
  conf$issue_tracker$github$project_key_1$commit <- sprintf("%s/commit/", base_path)
  conf$issue_tracker$github$project_key_1$commit_comments <- sprintf("%s/commit_comments/", base_path)
  conf$issue_tracker$github$project_key_1$pr_comments <- sprintf("%s/pr_comments/", base_path)

  conf
}

build_backup_path <- function(target_path, backup_dir = NULL) {
  stamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
  base_name <- basename(target_path)
  backup_name <- paste0(base_name, ".", stamp, ".bak")
  if (is.null(backup_dir)) return(file.path(dirname(target_path), backup_name))
  file.path(backup_dir, backup_name)
}

# Only prune YAML files that were generated by this script
is_script_generated_yaml <- function(path) {
  lines <- tryCatch(readLines(path, warn = FALSE, n = 20), error = function(e) character(0))
  any(grepl(generated_marker, lines, fixed = TRUE))
}

# Read GitHub token from file for API validation
read_github_token <- function(path) {
  token_file <- path.expand(path)
  if (!file.exists(token_file)) {
    stop("GitHub token file not found: ", token_file)
  }
  token <- readLines(token_file, warn = FALSE)
  token <- token[nzchar(token)][1]
  if (is.na(token) || token == "") {
    stop("GitHub token file is empty: ", token_file)
  }
  token
}

build_comment_api_url <- function(owner, repo, comment_id, source_tag) {
  if (source_tag == "commit_comment") {
    return(sprintf("https://api.github.com/repos/%s/%s/comments/%s", owner, repo, comment_id))
  }
  sprintf("https://api.github.com/repos/%s/%s/pulls/comments/%s", owner, repo, comment_id)
}

# Return HTTP status from the GitHub API
get_api_status <- function(url, token) {
  res <- httr::GET(
    url,
    httr::add_headers(
      Authorization = paste("token", token),
      Accept = "application/vnd.github+json"
    )
  )
  httr::status_code(res)
}

# Collect main repos and fork-only repos based on comment IDs from the MySQL database.
# Validate repos with fork-only comment IDs with the GitHub API.
fetch_repos_from_mysql <- function() {
  if (!requireNamespace("DBI", quietly = TRUE) || !requireNamespace("RMariaDB", quietly = TRUE)) {
    stop("MySQL mode requires DBI and RMariaDB packages. Install with: install.packages(c('DBI','RMariaDB'))")
  }

  host <- Sys.getenv("MYSQL_HOST", unset = "localhost")
  port <- as.integer(Sys.getenv("MYSQL_PORT", unset = "3306"))
  dbname <- Sys.getenv("MYSQL_DB", unset = "")
  user <- Sys.getenv("MYSQL_USER", unset = "")
  password <- Sys.getenv("MYSQL_PASSWORD", unset = "")

  if (dbname == "" || user == "") {
    stop("Set MYSQL_DB and MYSQL_USER environment variables for MySQL mode")
  }

  conn <- DBI::dbConnect(
    RMariaDB::MariaDB(),
    host = host,
    port = port,
    dbname = dbname,
    user = user,
    password = password
  )
  on.exit(DBI::dbDisconnect(conn), add = TRUE)

  # Query to get main repos + forks with fork-only comment IDs
  sql <- "
WITH RECURSIVE project_root AS (
    SELECT p.id AS project_id, p.id AS root_id
    FROM projects p
    WHERE p.forked_from IS NULL

    UNION ALL

    SELECT c.id AS project_id, pr.root_id
    FROM projects c
    JOIN project_root pr ON c.forked_from = pr.project_id
),
comment_project_rows AS (
    SELECT cs.ID AS comment_id, c.project_id, 'commit_comment' AS source_tag
    FROM comment_sentiment cs
    JOIN commit_comments cc ON cs.ID = cc.comment_id
    JOIN commits c ON cc.commit_id = c.id

    UNION ALL

    SELECT cs.ID AS comment_id, pr.base_repo_id AS project_id, 'pr_comment' AS source_tag
    FROM comment_sentiment cs
    JOIN pull_request_comments prc ON cs.ID = prc.comment_id
    JOIN pull_requests pr ON prc.pull_request_id = pr.id

    UNION ALL

    SELECT cs.ID AS comment_id, pr.head_repo_id AS project_id, 'pr_comment' AS source_tag
    FROM comment_sentiment cs
    JOIN pull_request_comments prc ON cs.ID = prc.comment_id
    JOIN pull_requests pr ON prc.pull_request_id = pr.id
),
labeled AS (
    SELECT
        cpr.comment_id,
        cpr.project_id,
        cpr.source_tag,
        pr.root_id,
        (cpr.project_id = pr.root_id) AS is_canonical
    FROM comment_project_rows cpr
    JOIN project_root pr ON pr.project_id = cpr.project_id
),
comment_flags AS (
    SELECT
        root_id,
        source_tag,
        comment_id,
        MAX(CASE WHEN is_canonical THEN 1 ELSE 0 END) AS has_canonical,
        MAX(CASE WHEN NOT is_canonical THEN 1 ELSE 0 END) AS has_fork
    FROM labeled
    GROUP BY root_id, source_tag, comment_id
),
fork_only_comments AS (
    SELECT root_id, source_tag, comment_id
    FROM comment_flags
    WHERE has_fork = 1 AND has_canonical = 0
),
canonical_repos AS (
    SELECT DISTINCT root_id AS project_id, 'canonical' AS include_reason
    FROM labeled
),
fork_repos_to_include AS (
    SELECT DISTINCT l.project_id, 'fork_only_unique_comments' AS include_reason
    FROM labeled l
    JOIN fork_only_comments f
      ON f.root_id = l.root_id
     AND f.source_tag = l.source_tag
     AND f.comment_id = l.comment_id
    WHERE l.project_id <> l.root_id
),
final_projects AS (
    SELECT * FROM canonical_repos
    UNION
    SELECT * FROM fork_repos_to_include
)
SELECT LOWER(u.login) AS owner,
       LOWER(p.name) AS repo,
       fp.include_reason
FROM final_projects fp
JOIN projects p ON p.id = fp.project_id
JOIN users u ON u.id = p.owner_id
ORDER BY owner, repo
"

  fork_only_sql <- "
WITH RECURSIVE project_root AS (
  SELECT p.id AS project_id, p.id AS root_id
  FROM projects p
  WHERE p.forked_from IS NULL

  UNION ALL

  SELECT c.id AS project_id, pr.root_id
  FROM projects c
  JOIN project_root pr ON c.forked_from = pr.project_id
),
comment_project_rows AS (
  SELECT cs.ID AS comment_id, c.project_id, 'commit_comment' AS source_tag
  FROM comment_sentiment cs
  JOIN commit_comments cc ON cs.ID = cc.comment_id
  JOIN commits c ON cc.commit_id = c.id

  UNION ALL

  SELECT cs.ID AS comment_id, pr.base_repo_id AS project_id, 'pr_comment' AS source_tag
  FROM comment_sentiment cs
  JOIN pull_request_comments prc ON cs.ID = prc.comment_id
  JOIN pull_requests pr ON prc.pull_request_id = pr.id

  UNION ALL

  SELECT cs.ID AS comment_id, pr.head_repo_id AS project_id, 'pr_comment' AS source_tag
  FROM comment_sentiment cs
  JOIN pull_request_comments prc ON cs.ID = prc.comment_id
  JOIN pull_requests pr ON prc.pull_request_id = pr.id
),
labeled AS (
  SELECT
    cpr.comment_id,
    cpr.project_id,
    cpr.source_tag,
    pr.root_id,
    (cpr.project_id = pr.root_id) AS is_canonical
  FROM comment_project_rows cpr
  JOIN project_root pr ON pr.project_id = cpr.project_id
),
comment_flags AS (
  SELECT
    root_id,
    source_tag,
    comment_id,
    MAX(CASE WHEN is_canonical THEN 1 ELSE 0 END) AS has_canonical,
    MAX(CASE WHEN NOT is_canonical THEN 1 ELSE 0 END) AS has_fork
  FROM labeled
  GROUP BY root_id, source_tag, comment_id
),
fork_only_comments AS (
  SELECT root_id, source_tag, comment_id
  FROM comment_flags
  WHERE has_fork = 1 AND has_canonical = 0
)
SELECT
  LOWER(fu.login) AS fork_owner,
  LOWER(fp.name) AS fork_repo,
  LOWER(cu.login) AS canonical_owner,
  LOWER(cp.name) AS canonical_repo,
  f.source_tag,
  f.comment_id
FROM fork_only_comments f
JOIN labeled l
  ON l.comment_id = f.comment_id
 AND l.root_id = f.root_id
 AND l.source_tag = f.source_tag
 AND l.project_id <> l.root_id
JOIN projects fp ON fp.id = l.project_id
JOIN users fu ON fu.id = fp.owner_id
JOIN projects cp ON cp.id = f.root_id
JOIN users cu ON cu.id = cp.owner_id
"

  dt <- data.table::as.data.table(DBI::dbGetQuery(conn, sql))
  fork_dt <- data.table::as.data.table(DBI::dbGetQuery(conn, fork_only_sql))
  list(repos = unique(dt, by = c("owner", "repo")), fork_candidates = fork_dt)
}

repo_data <- fetch_repos_from_mysql()
repo_dt <- repo_data$repos
fork_candidates <- repo_data$fork_candidates

api_excluded_forks <- 0
if (verify_api) {
  if (!requireNamespace("httr", quietly = TRUE)) {
    stop("API validation requires httr. Install with: install.packages('httr')")
  }

  # Validate fork-only comment IDs against the GitHub API
  token <- read_github_token(token_path)
  sample_size <- if (is.na(sample_size) || sample_size < 1) 3L else sample_size

  if (nrow(fork_candidates) == 0) {
    warning("API validation enabled, but no fork candidates were returned from MySQL")
  } else {
    fork_candidates <- fork_candidates[order(comment_id)]
    fork_groups <- unique(fork_candidates[, .(fork_owner, fork_repo, canonical_owner, canonical_repo)])
    if (!is.na(max_forks) && max_forks > 0 && nrow(fork_groups) > max_forks) {
      fork_groups <- head(fork_groups, max_forks)
    }
    keep_forks <- rep(FALSE, nrow(fork_groups))

    for (i in seq_len(nrow(fork_groups))) {
      f_owner <- fork_groups$fork_owner[[i]]
      f_repo <- fork_groups$fork_repo[[i]]
      canonical_owner <- fork_groups$canonical_owner[[i]]
      canonical_repo <- fork_groups$canonical_repo[[i]]

      # Test a small sample of comment IDs per fork
      candidates <- fork_candidates[fork_owner == f_owner & fork_repo == f_repo]
      candidates <- head(candidates, sample_size)

      for (j in seq_len(nrow(candidates))) {
        comment_id <- candidates$comment_id[[j]]
        source_tag <- candidates$source_tag[[j]]

        fork_url <- build_comment_api_url(f_owner, f_repo, comment_id, source_tag)
        canonical_url <- build_comment_api_url(canonical_owner, canonical_repo, comment_id, source_tag)

        fork_status <- get_api_status(fork_url, token)
        canonical_status <- get_api_status(canonical_url, token)

        if (fork_status == 200 && canonical_status %in% c(404, 410)) {
          keep_forks[[i]] <- TRUE
          break
        }

        if (fork_status == 403 || canonical_status == 403) {
          stop("GitHub API rate limit or permission issue (403). Try again later or use a different token.")
        }
      }
    }

    fork_groups[, keep := keep_forks]
    keep_map <- fork_groups[keep == TRUE, .(fork_owner, fork_repo)]
    before_count <- nrow(repo_dt)
    # Drop fork repos that fail API validation
    repo_dt <- repo_dt[!(include_reason == "fork_only_unique_comments" &
                         owner %in% fork_groups$fork_owner & repo %in% fork_groups$fork_repo) |
                         (owner %in% keep_map$fork_owner & repo %in% keep_map$fork_repo)]
    api_excluded_forks <- before_count - nrow(repo_dt)
  }
}

if (nrow(repo_dt) == 0) {
  stop("No repositories returned by source mode: ", source_mode)
}

template_conf <- yaml::read_yaml(template_path)

# Clean owner/repo text, remove duplicates, then compute each output file path
planned <- repo_dt[, .(
  owner = tolower(trimws(owner)),
  repo = tolower(trimws(repo)),
  include_reason = if ("include_reason" %in% names(repo_dt)) include_reason else NA_character_
)]
planned <- planned[owner != "" & repo != ""]
planned <- unique(planned, by = c("owner", "repo"))
planned[, filename := mapply(build_filename, owner, repo, USE.NAMES = FALSE)]
planned[, target := file.path(out_dir, filename)]

if (verbose) {
  message("Source mode: ", source_mode)
  message("Unique owner/repo pairs: ", nrow(planned))
  if ("include_reason" %in% names(planned)) {
    reason_tab <- planned[, .N, by = include_reason][order(include_reason)]
    for (i in seq_len(nrow(reason_tab))) {
      message("  include_reason ", reason_tab$include_reason[[i]], ": ", reason_tab$N[[i]])
    }
  }
  message("Mode: ", ifelse(apply_changes, "apply", "dry-run"))
  message("Prune out-of-scope generated files: ", ifelse(prune_out_of_scope, "enabled", "disabled"))
  if (verify_api) {
    message("API validation excluded forks: ", api_excluded_forks)
  }
}

created_count <- 0
replaced_count <- 0
backup_count <- 0
error_count <- 0
pruned_count <- 0

# If --apply is set, write YAML files
for (i in seq_len(nrow(planned))) {
  owner <- planned$owner[[i]]
  repo <- planned$repo[[i]]
  target <- planned$target[[i]]

  conf <- build_conf(template_conf, owner, repo)

  if (!apply_changes) next

  if (file.exists(target)) {
    backup_path <- build_backup_path(target, backup_dir)
    copied <- file.copy(target, backup_path, overwrite = FALSE)
    if (!copied) {
      warning("Failed to create backup for existing file: ", target)
      error_count <- error_count + 1
      next
    }
    backup_count <- backup_count + 1
    replaced_count <- replaced_count + 1
  } else {
    created_count <- created_count + 1
  }

  yaml_text <- yaml::as.yaml(conf)
  writeLines(c(yaml_header, "", yaml_text), target, useBytes = TRUE)
}

if (apply_changes && prune_out_of_scope) {
  # Remove previously generated YAMLs that are no longer in scope
  all_yml <- list.files(out_dir, pattern = "\\.yml$", full.names = TRUE)
  generated_yml <- all_yml[sapply(all_yml, is_script_generated_yaml)]
  in_scope <- planned$target
  to_delete <- setdiff(generated_yml, in_scope)

  if (length(to_delete) > 0) {
    deleted <- file.remove(to_delete)
    pruned_count <- sum(deleted)
    error_count <- error_count + sum(!deleted)
  }
}

cat("SUMMARY\n")
cat("source=", source_mode, "\n", sep = "")
cat("pairs_total=", nrow(planned), "\n", sep = "")
cat("mode=", ifelse(apply_changes, "apply", "dry-run"), "\n", sep = "")

if (apply_changes) {
  cat("created=", created_count, "\n", sep = "")
  cat("replaced=", replaced_count, "\n", sep = "")
  cat("backups_created=", backup_count, "\n", sep = "")
  cat("pruned_out_of_scope_generated=", pruned_count, "\n", sep = "")
  if (verify_api) {
    cat("api_excluded_forks=", api_excluded_forks, "\n", sep = "")
  }
  cat("errors=", error_count, "\n", sep = "")
} else {
  cat("would_generate=", nrow(planned), "\n", sep = "")
  cat("note=use --apply to write files\n")
}
