---
title: "Download Mod Mbox Mailing List Archives"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Download Mod Mbox Mailing List Archives}
  %\VignetteEncoding{UTF-8}
---


```{r}
rm(list = ls())
seed <- 1
set.seed(seed)
```

```{r warning=FALSE,message=FALSE}
require(kaiaulu)
require(data.table)
```

# Introduction

Mailing list data is stored in a variety of archives (e.g. see [Apache Geronimo](https://geronimo.apache.org/mailing-lists.html)). This notebook showcases how to obtain data from mod_mbox archives, which is adopted by the Apache Software Foundation.

## Project Configuration File 

As usual, the first step is to load the project configuration file. 

# Project Configuration File

```{r}
conf <- yaml::read_yaml("../conf/helix.yml")
save_path_mbox <- conf[["mailing_list"]][["mod_mbox"]][["mail_key_1"]][["mbox"]]
mod_mbox_url <- conf[["mailing_list"]][["mod_mbox"]][["mail_key_1"]][["archive_url"]]
mailing_list <- conf[["mailing_list"]][["mod_mbox"]][["mail_key_1"]][["mailing_list"]]
archive_type <- conf[["mailing_list"]][["mod_mbox"]][["mail_key_1"]][["archive_type"]]
start_year <- 2017
end_year <- 2018
```

```{r eval = FALSE}
mbox <- download_mod_mbox_per_month(archive_url = mod_mbox_url, 
                          mailing_list = mailing_list,
                          archive_type = archive_type,
                          from_year=start_year,
                          to_year=end_year,
                          save_folder_path = save_path_mbox,
                          verbose = TRUE)
```

```{r eval = FALSE}
mbox_latest <- parse_mbox_latest_date(save_path_mbox)
refresh_mbox(archive_url = mod_mbox_url, 
             mailing_list = mailing_list, 
             archive_type = archive_type, 
             from_year = start_year,
             save_folder_path = save_path_mbox, 
             verbose = TRUE)
```
