---
title: "Event Process Mining"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Event Process Mining}
  %\VignetteEncoding{UTF-8}
---

# Introduction

The `ghevents.R` script provides a command-line interface (CLI) for downloading and parsing GitHub event data using R. It is a part of the **Kaiaulu** project and is designed to facilitate the retrieval and processing of GitHub project issue events. By leveraging R libraries such as `yaml`, `cli`, `docopt`, `kaiaulu`, `data.table`, and `jsonlite`, this script offers an efficient way to manage GitHub event data. This data can be used for various analysis and use cases. This vignette shows how to access the CLI, to see a use case for process mining refer to this [repo](https://github.com/sailuh/process_mining).

## Requirements

-   Gihub Access Token
-   Python (for visualizations)
-   Python environment with [pm4py](https://github.com/process-intelligence-solutions/pm4py) installed

## Project Configuration File

To streamline downloading and parsing data for Github Events we will specify a configuration file instead of entering parameters manually for both R and python environments. You can use the Kaiaulu.yml configuration file as a template. The configuration file content that interests us are the following:

-   Github owner and repo names along with the issue_event as it provides the save path for the Github API

    ```         
    github:
        project_key_1:
          # Obtained from the project's GitHub URL
          owner: sailuh
          repo: kaiaulu
          # Download using `download_github_comments.Rmd`
          issue_or_pr_comment: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_or_pr_comment/
          issue: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue/
          issue_search: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_search/
          issue_event: ../rawdata/kaiaulu/github/sailuh_kaiaulu/issue_event/
          pull_request: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/pull_request/
          commit: ../../rawdata/kaiaulu/github/sailuh_kaiaulu/commit/
    ```

### Download and Parse data with kaiaulu ghevents.R (CLI)

-   To download specify: \<config_file\> \<github_token\>

-   To parse specify \<config_file\>

```{r}
command <- 'Rscript exec/ghevents.R download conf/process_mining.yml --token_path=~/.ssh/github_token'
system(command)

command <- 'Rscript exec/ghevents.R parse ../output ../output.csv'
system(command)
```

### Generate tree and graphs from data

```         
python event_processing.py ../kaiaulu/conf/process_mining.yml generate_tree
python event_processing.py ../kaiaulu/conf/process_mining.yml generate_graph
```
