---
title: "Collaboration Network Parser"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Collaboration Network Parser}
  %\VignetteEncoding{UTF-8}
---

```{r}
rm(list = ls())
seed <- 1
set.seed(seed)
```

```{r warning=FALSE,message=FALSE}
require(kaiaulu)
require(visNetwork)
require(reactable)
require(data.table)
require(igraph)
require(yaml)
require(stringi)
```

Load config file.

```{r}
tool <- yaml::read_yaml("../tools.yml")
conf <- yaml::read_yaml("../conf/apr.yml")
perceval_path <- tool[["perceval"]]
git_repo_path <- conf[["data_path"]][["git"]]
nvdfeed_folder_path <- conf[["data_path"]][["nvd_feed"]]

# Filters
file_extensions <- conf[["filter"]][["keep_filepaths_ending_with"]]
substring_filepath <- conf[["filter"]][["remove_filepaths_containing"]]
```

# Construct Contribution Network

```{r}
#save_path <- "/Users/cvp/Desktop/kaiaulu_project_input/rds/APR_git.rds"
project_git <- parse_gitlog(perceval_path,git_repo_path)
#project_git <- parse_gitlog(perceval_path,git_repo_path,save_path)
#project_git <- readRDS(save_path)
```

# Filter files

```{r}
project_git <- project_git  %>%
  filter_by_file_extension(file_extensions,"file")  %>% 
  filter_by_filepath_substring(substring_filepath,"file")
```

# Identity

```{r}
project_git[,c("name","raw_name"):=list(assign_exact_identity(data.Author),data.Author)]
```


```{r}
project_git_slice <- project_git[data.AuthorDate >= as.POSIXct("2019-01-01", format = "%Y-%m-%d",tz = "UTC") & data.AuthorDate < as.POSIXct("2019-12-31", format = "%Y-%m-%d",tz = "UTC")]


project_contribution_network <- parse_gitlog_network(project_git_slice,mode="author-committer")
project_contribution_network <- igraph::graph_from_data_frame(d=project_contribution_network[["edgelist"]], 
                      directed = TRUE, 
                      vertices = project_contribution_network[["nodes"]])
visIgraph(project_contribution_network,randomSeed = 1)
```

# Parse Gitlog Temporal Network

```{r}
project_temporal_collaboration_network <- parse_gitlog_temporal_network(project_git_slice)
project_temporal_collaboration_network <- igraph::graph_from_data_frame(d=project_temporal_collaboration_network[["edgelist"]], 
                      directed = TRUE, 
                      vertices = project_temporal_collaboration_network[["nodes"]])
visIgraph(project_temporal_collaboration_network,randomSeed = 1)
```


# Construct a Commit-File Network

```{r}
project_commit_network <- parse_gitlog_network(project_git_slice,mode="commit")
project_commit_network <- igraph::graph_from_data_frame(d=project_commit_network[["edgelist"]], 
                      directed = TRUE, 
                      vertices = project_commit_network[["nodes"]])
visIgraph(project_commit_network,randomSeed = 1)
```

# Co-Change Network

```{r}
co_change_network <- igraph::bipartite_projection(project_commit_network,
                                          multiplicity = TRUE,
                                          which = FALSE) # FALSE is the file projection
visIgraph(co_change_network,randomSeed = 1)
```

```{r eval = FALSE,include=FALSE}
## Co-Change adjacency matrix 
reactable(as_adjacency_matrix(co_change_network,attr = "weight",sparse = F))
```
