---
title: "Identity Showcase"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Identity Showcase}
  %\VignetteEncoding{UTF-8}
---

```{r}
rm(list = ls())
seed <- 1
set.seed(seed)
```

```{r warning=FALSE,message=FALSE}
require(kaiaulu)
require(data.table)
require(stringi)
require(igraph)
require(knitr)
require(visNetwork)
```

Load config file.

```{r}
tool <- yaml::read_yaml("../tools.yml")
conf <- yaml::read_yaml("../conf/apr.yml")
perceval_path <- tool[["perceval"]]
git_repo_path <- conf[["data_path"]][["git"]]
mbox_path <- conf[["data_path"]][["mbox"]]
```


Obtain edgelist 

```{r}
project_git <- parse_gitlog(perceval_path,git_repo_path)
project_mbox <- parse_mbox(perceval_path,mbox_path)
```

Specify the commit interval of interest

```{r}
start_commit <- "9eae9e96f15e1f216162810cef4271a439a74223"
end_commit <- "f1d2d568776b3708dd6a3077376e2331f9268b04"

interval_timestamps <- project_git[data.commit %in% c(start_commit,end_commit)]$data.AuthorDate
start_date <- interval_timestamps[1]
end_date <- interval_timestamps[2]

project_git <- project_git[data.AuthorDate >= start_date & data.AuthorDate <= end_date]
project_mbox <- project_mbox[data.Date >= start_date & data.Date <= end_date]
```

Assign common identity (id) to both networks authors

```{r}
all_name_emails <- unique(c(project_git$data.Author,project_mbox$data.From))
name_mapping <- data.table(raw_name=all_name_emails,identity_id=assign_exact_identity(all_name_emails,use_name_only = FALSE))
project_git <- merge(project_git,name_mapping,by.x="data.Author",by.y="raw_name")
project_mbox <- merge(project_mbox,name_mapping,by.x="data.From",by.y="raw_name")
name_mapping[,.(raw_name = stri_c(raw_name,collapse = " | ")),by="identity_id"]
```


Parse networks edgelist from extracted data

```{r}
project_git_network <- parse_gitlog_network(project_git,mode="author")
project_mbox_network <- parse_mbox_network(project_mbox)
```




Load networks in igraph

```{r}
project_git_network <- igraph::graph_from_data_frame(d=project_git_network[["edgelist"]], 
                      directed = TRUE, 
                      vertices = project_git_network[["nodes"]])
project_mbox_network <- igraph::graph_from_data_frame(d=project_mbox_network[["edgelist"]], 
                      directed = TRUE, 
                      vertices = project_mbox_network[["nodes"]])
```



We can also obtain the projection networks of dev-thread => dev-dev, and dev-file => dev-dev.

```{r}
git_network_authors <- igraph::bipartite_projection(project_git_network,
                                          multiplicity = TRUE,
                                          which = TRUE) # FALSE is the thread projection

mbox_network_authors <- igraph::bipartite_projection(project_mbox_network,
                                          multiplicity = TRUE,
                                          which = TRUE) # FALSE is the thread projection
```

# Networks after Identity Mapping

```{r}
visNetwork::visIgraph(project_git_network,randomSeed = 1)
```


```{r}
visIgraph(git_network_authors,randomSeed = 1)
```



```{r}
visIgraph(project_mbox_network,randomSeed = 1)
```

```{r}
visIgraph(mbox_network_authors,randomSeed = 1)
```

