---
title: "Collaboration Network Parser"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Collaboration Network Parser}
  %\VignetteEncoding{UTF-8}
---

```{r}
rm(list = ls())
seed <- 1
set.seed(seed)
```

```{r warning=FALSE,message=FALSE}
require(kaiaulu)
require(visNetwork)
require(reactable)
```

```{r}
perceval_path <- "/Users/cvp/Desktop/kaiaulu/kaiaulu_env/bin/perceval"
```

# Construct Contribution Network

```{r}
git_repo_path <- "/Users/cvp/Desktop/kaiaulu_project_input/APR/.git"
save_path <- "/Users/cvp/Desktop/kaiaulu_project_input/rds/APR_git.rds"
#project_git <- parse_gitlog(perceval_path,git_repo_path,save_path)
project_git <- readRDS(save_path)
```

```{r}
project_git <- project_git[data.AuthorDate >= as.POSIXct("2019-01-01", format = "%Y-%m-%d",tz = "UTC") & data.AuthorDate < as.POSIXct("2019-12-31", format = "%Y-%m-%d",tz = "UTC")]
project_contribution_network <- parse_gitlog_igraph(project_git,mode="author")
visIgraph(project_contribution_network,randomSeed = 1)
```


# Construct a Commit-File Network

```{r}
project_commit_network <- parse_gitlog_igraph(project_git,mode="commit")
visIgraph(project_commit_network,randomSeed = 1)
```

# Co-Change Network

```{r}
co_change_network <- bipartite_projection(project_commit_network,
                                          multiplicity = TRUE,
                                          which = FALSE) # FALSE is the file projection
visIgraph(co_change_network,randomSeed = 1)
```

## Co-Change adjacency matrix 

```{r eval = FALSE}
reactable:reactable(as_adjacency_matrix(co_change_network,attr = "weight",sparse = F))
```




# Construct Communication Network

```{r eval = FALSE}
mbox_path <- "/Users/cvp/Desktop/kaiaulu_project_input/apr-dev.mbox"
apr_mbox <- parse_mbox(perceval_path,mbox_path)
apr_communication_network <- parse_mbox_igraph(apr_mbox)
visIgraph(apr_communication_network,randomSeed = 1)
```

