---
title: "Parallel Parsing of Mbox Files Using Python and R"
output: 
  html_document:
    toc: true
    number_sections: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Parallel Parsing of Mbox Files Using Python and R}
  %\VignetteEncoding{UTF-8}
---

rm(list = ls())
seed <- 1
set.seed(seed)

# Load required libraries
require(kaiaulu)
require(data.table)
require(yaml)
require(cli)

# Introduction
This notebook demonstrates how to efficiently parse .mbox files using parallel processing. Python's ThreadPoolExecutor handles the parallel parsing of multiple .mbox files using an R script (parsembox.R) through a Python wrapper. This allows concurrent processing of mailing list archives, which is useful when dealing with large datasets.

# Prerequisites
1. A collection of .mbox files to parse (see download_mail.Rmd for help with this)
2. Perceval

## Project Configuration File 

```{r}
tools_config <- yaml::read_yaml("tools.yml")
perceval_path <- tools_config[["perceval"]]

conf <- yaml::read_yaml("conf/helix.yml")
save_folder_path <- conf[["mailing_list"]][["pipermail"]][["project_key_1"]][["save_folder_path"]]
```

## Python Thread Manager
We will use the parse_mbox.py Python script to execute the parsing of multiple .mbox files in parallel. The Python script uses the ThreadPoolExecutor to run the R script (parsembox.R) concurrently on each .mbox file.

Here is how it works:

1. Python's ThreadPoolExecutor is used to handle parallel processing.
2. Each thread calls the R script for one .mbox file.
3. The R script processes the file and saves the output as a CSV file.

```{bash}
python3 parse_mbox.py
```
