command_template:
  - "Rscript"
  - "{exec_script}"
  - "parse"
  - "{tools_yml}"
  - "{input_file}"
  - "{output_file}"
exec_script: "../../exec/mailinglist.R"
tools_yml: "../../tools.yml"
input_dir: "../../../rawdata/helix/mod_mbox/save_mbox_mail"
output_dir: "../../../rawdata/helix/mod_mbox/parsed_mbox_mail"
input_file_extension: ".mbox"
num_threads: 4
process_individual_files: true
