# Kaiaulu - https://github.com/sailuh/kaiaulu
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#' Performs a git checkout on specified repo
#'
#' @param commit_hash The commit hash the repo should be checkout
#' @param git_repo_path The git repo path
#' @return Any error message generated by git
#' @export
git_checkout <- function(commit_hash,git_repo_path){
  # Expand paths (e.g. "~/Desktop" => "/Users/someuser/Desktop")
  git_repo_path <- path.expand(git_repo_path)
  # Remove ".git"
  folder_path <- stri_replace_last(git_repo_path,replacement="",regex=".git")
  error <- system2('git',
                  args = c('--git-dir',
                           git_repo_path,
                           '--work-tree',
                           folder_path,
                           'checkout',
                           commit_hash),
                  stdout = TRUE,
                  stderr = FALSE)
  return(error)
}
#' Gets the current commit hash head of the git repo
#'
#' @param git_repo_path The git repo path
#' @return A commit hash character
#' @export
git_head <- function(git_repo_path){
  # Expand paths (e.g. "~/Desktop" => "/Users/someuser/Desktop")
  git_repo_path <- path.expand(git_repo_path)
  head <- system2('git',
                  args = c('--git-dir',
                           git_repo_path,
                           'rev-parse',
                           'HEAD'),
                  stdout = TRUE,
                  stderr = FALSE)
  return(head)
}
#' Saves gitlog to a path
#'
#' @param git_repo_path The git repo path
#' @param flags Optional flags for git log command
#' @param save_path the filepath to save the file
#' @export
git_log <- function(git_repo_path,flags,save_path){
  system2(
    "git",
    args = c(
      '--git-dir',
      git_repo_path,
      'log',
      flags,
      '>' ,
      save_path
    ),
    stdout = TRUE,
    stderr = FALSE
  )
}
#' Git blame wrapper
#'
#' @param git_repo_path The git repo pat
#' @param flags Optional flags for git log command
#' @param commit_hash The commit hash of the file we will blame
#' @param file_path The file we will blame
#' @export
git_blame <- function(git_repo_path,flags,commit_hash,file_path){

  # Some commit hashes, like APR's project git 572
  # throws error 128 from git
  # 6154ab7b1e862927c90ae6afa4dc6c57ee657ceb

  # This example changes function signature and a line inside
  # https://github.com/apache/apr/commit/ffdad353ac4b4bc2868603338e8ca50db90923a8
  blamed_file <- tryCatch({
    system2(
      "git",
      args = c(
        '--git-dir',
        git_repo_path,
        'blame',
        flags,
        commit_hash,
        file_path
      ),
      stdout = TRUE,
      stderr = FALSE
    )
  },
  warning = function(e) {
    #message(e)
    return(NULL)
  })
  # Blamed file was deleted by the commit
  if(is.character(blamed_file) & length(blamed_file) == 0){return(NULL)}
  return(blamed_file)


}
